# Dockerfile to build R_base container images

FROM dmccloskey/r-base:latest

# File Author / Maintainer
MAINTAINER Douglas McCloskey <dmccloskey87@gmail.com>

# Switch to root for install
USER root

# install R packages
RUN Rscript -e 'install.packages("e1071",dependencies=TRUE)' \
	&&Rscript -e 'install.packages("Amelia",dependencies=TRUE)' \
	&&Rscript -e 'install.packages("mixOmics",dependencies=TRUE)' \
	&&Rscript -e 'install.packages("pls",dependencies=TRUE)' \
	&&Rscript -e 'install.packages("spls",dependencies=TRUE)' \
	&&Rscript -e 'install.packages("caret",dependencies=TRUE)' \
#	&&Rscript -e 'install.packages("RVAideMemoire",dependencies=TRUE)' \
	&&Rscript -e 'install.packages("coin",dependencies=TRUE)' \

## install devtools using R
	&&Rscript -e 'install.packages("devtools")'

## install additional R packages using R
RUN > rscript.R \
	&&echo 'source("http://bioconductor.org/biocLite.R")' >> rscript.R \
#	&&echo 'biocLite("BiocUpgrade")' >> rscript.R \
	&&echo 'biocLite("Biobase",ask=FALSE)' >> rscript.R \
	&&echo 'biocLite("LMGene",ask=FALSE)' >> rscript.R \
	&&echo 'biocLite("pcaMethods",ask=FALSE)' >> rscript.R \
	&&echo 'biocLite("ropls",ask=FALSE)' >> rscript.R \
	&&echo 'biocLite("pcaMethods",ask=FALSE)' >> rscript.R \
	&&Rscript rscript.R

# Cleanup
RUN rm rscript.R

# Switch back to user
WORKDIR $HOME
USER user

# set the command
CMD ["R"]